[package]
name = "musicbee_function_converter"
version = "0.1.0"
authors = ["Gremious"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"